#!/bin/sh
set -x

switch=br0

if [ -n "$1" ];then
        ip link set $1 up
        sleep 0.5s
        brctl addif $switch $1
        sleep 5s
        exit 0
else
        echo "Error: no interface specified"
        sleep 5s
        exit 1
fi
